Organizations:
 
    - &OrdererOrg
        Name: OrdererOrg
 
        ID: OrdererMSP
 
        MSPDir: crypto-config/ordererOrganizations/zju.com/msp
 
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
                
        OrdererEndpoints:
            - orderer.zju.com:7050
    - &Org1
 
        Name: Org1MSP
 
        ID: Org1MSP
 
        MSPDir: crypto-config/peerOrganizations/org1.zju.com/msp
 
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
 
        AnchorPeers:
            - Host: peer0.org1.zju.com
              Port: 7051
 
    - &Org2
 
        Name: Org2MSP
 
        ID: Org2MSP
 
        MSPDir: crypto-config/peerOrganizations/org2.zju.com/msp
 
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
 
        AnchorPeers:
            - Host: peer0.org2.zju.com
              Port: 9051
 
    - &OrgCa
 
        Name: OrgCaMSP
 
        ID: OrgCaMSP
 
        MSPDir: crypto-config/peerOrganizations/orgca.zju.com/msp
 
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgCaMSP.admin', 'OrgCaMSP.peer', 'OrgCaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgCaMSP.admin', 'OrgCaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgCaMSP.admin')"
 
        AnchorPeers:
            - Host: peer0.orgca.zju.com
              Port: 11051
 
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
 
    Orderer: &OrdererCapabilities
        V2_0: true
 
    Application: &ApplicationCapabilities
        V2_0: true
 
Application: &ApplicationDefaults
 
    Organizations:
 
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
 
    Capabilities:
        <<: *ApplicationCapabilities
        
Orderer: &OrdererDefaults
 
    OrdererType: etcdraft
    
    Addresses:
        - orderer.zju.com:7050
        
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
 
    EtcdRaft:
        Consenters:
            - Host: orderer.zju.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer.zju.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer.zju.com/tls/server.crt
            - Host: orderer2.zju.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer2.zju.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer2.zju.com/tls/server.crt
            - Host: orderer3.zju.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer3.zju.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer3.zju.com/tls/server.crt
 
    Organizations:
 
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
            
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
 
    Capabilities:
        <<: *ChannelCapabilities
 
Profiles:
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities:
                <<: *ApplicationCapabilities
    
    CertChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *OrgCa
            Capabilities:
                <<: *ApplicationCapabilities
    
    OrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
                - *OrgCa
                
                
    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.zju.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer.zju.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer.zju.com/tls/server.crt
                - Host: orderer2.zju.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer2.zju.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer2.zju.com/tls/server.crt
                - Host: orderer3.zju.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer3.zju.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/zju.com/orderers/orderer3.zju.com/tls/server.crt
            Addresses:
                - orderer.zju.com:7050
                - orderer2.zju.com:7050
                - orderer3.zju.com:7050
            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
                - *OrgCa
