OrdererOrgs:
  - Name: Orderer
    Domain: zju.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
PeerOrgs:
  - Name: Org1
    Domain: org1.zju.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.zju.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: OrgCa
    Domain: orgca.zju.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
